apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    {{- include "user-mgmt-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          ports:
            - containerPort: {{ .Values.backend.service.port }}
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SPRING_JPA_HIBERNATE_DDL_AUTO
            - name: JWT_ISSUER
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: JWT_ISSUER
            - name: JWT_EXPIRATION_MILLIS
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: JWT_EXPIRATION_MILLIS
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: SPRING_DATASOURCE_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: JWT_SECRET
