apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    {{- include "user-mgmt-service.labels" . | nindent 4 }}
spec:
  selector:
    app: backend
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.port }}
  type: ClusterIP
