apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    {{- include "user-mgmt-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          ports:
            - containerPort: {{ .Values.frontend.service.targetPort }}
          env:
            - name: INTERNAL_API_URL
              value: "http://backend-service:{{ .Values.backend.service.port }}"
