spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.issuer=${JWT_ISSUER}
jwt.secret=${JWT_SECRET}
jwt.expiration-millis=${JWT_EXPIRATION_MILLIS}

# Actuator / Prometheus
management.endpoints.web.exposure.include=health,prometheus
management.endpoint.health.enabled=true
management.endpoint.prometheus.enabled=true

# Module Service
module-service.base-url=${MODULE_SERVICE_BASE_URL:http://module-service:8080}

# Retry
resilience4j.retry.instances.moduleService.max-attempts=3
resilience4j.retry.instances.moduleService.wait-duration=500ms

# Circuit Breaker
resilience4j.circuitbreaker.instances.moduleService.sliding-window-size=5
resilience4j.circuitbreaker.instances.moduleService.minimum-number-of-calls=3
resilience4j.circuitbreaker.instances.moduleService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.moduleService.wait-duration-in-open-state=10s
