apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-service:5432/postgres
  SPRING_DATASOURCE_USERNAME: postgres
  SPRING_JPA_HIBERNATE_DDL_AUTO: create
  JWT_ISSUER: Spring
  JWT_EXPIRATION_MILLIS: "86400000"
  POSTGRES_DB: postgres
